name: Test and Release Cross-Platform

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'  # Match version tags like v0.1.0, v1.2.3, etc.
  pull_request:
    branches:
      - master
      
permissions:
  contents: write

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build Project
      run: cargo build --release

    - name: Run Tests
      run: cargo test

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: target/release/vex2pdf

  windows-build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build Project
      run: cargo build --release

    - name: Run Tests
      run: cargo test

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: target/release/vex2pdf.exe

  create-release:
    name: Create Release
    needs: [linux-build, windows-build]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-build
          path: ./linux/
      
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: ./windows/
          
      - name: Rename artifacts with architecture
        run: |
          mv ./linux/vex2pdf ./vex2pdf-linux-x86_64
          mv ./windows/vex2pdf.exe ./vex2pdf-windows-x86_64.exe
          chmod +x ./vex2pdf-linux-x86_64
          
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release Binaries v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            ./vex2pdf-linux-x86_64
            ./vex2pdf-windows-x86_64.exe
          body: |
            # vex2pdf v${{ steps.get_version.outputs.VERSION }}
            
            This release provides pre-built binaries for Linux and Windows.
            
            ## Included Binaries
            
            - **Linux (x86_64)**: `vex2pdf-linux-x86_64`
            - **Windows (x86_64)**: `vex2pdf-windows-x86_64.exe`
            
            ## Installation
            
            - Download the appropriate binary for your platform
            - Make it executable (Linux: `chmod +x vex2pdf-linux-x86_64`)
            - Run the tool in a directory with CycloneDX VEX JSON files
            
            ## Font Requirement
            
            Remember that this tool requires Liberation Sans fonts to render PDFs correctly.
            See the [README](https://github.com/${{ github.repository }}/blob/master/README.md#-font-requirement) for details.
            
            For full documentation, see the [README](https://github.com/${{ github.repository }}/blob/master/README.md).
